### ISSUE TITLE
Ubuntu 18.04 npm install & peer dependencies

### ISSUE THREAD

**Issue by xelcho** [LeadingEdgeForum/atlas2#342]
When I follow the directions to run as a dev I hit these issues:

$ npm install
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-bootstrap-slider@2.2.2 requires a peer of bootstrap@^3.3.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-bootstrap@0.24.4 requires a peer of react-router-dom@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-stepzilla@4.8.0 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-stepzilla@4.8.0 requires a peer of react-dom@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN wdio-webpack-service@1.0.1 requires a peer of webpack@1.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

When I do run npm start, it starts but has issues. The gui has artifacts etc.
Output from npm start:

$ npm start  

> Atlas2@3.0.0-gamma1 start /home/userw/atlas2
> node src-server/app.js

[2019-07-07T09:46:25.619] [WARN] tracker-helper - tracking not configured
[2019-07-07T09:46:25.623] [WARN] freshdesk-helper - freshdesk not configured
[2019-07-07T09:46:25.880] [WARN] mongodb-helper - mongoDB service not configured (or configured improperly), defaulting to local database
starting migration
using password
using l-p
[2019-07-07T09:46:26.373] [TRACE] user-provider - Using passport anonymous user provider
Custom licence not found { Error: Cannot find module '../../tos-content-custom.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/userw/atlas2/src-server/tos/tos.js:22:21)
    at Object.<anonymous> (/home/userw/atlas2/src-server/app.js:194:44)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 code: 'MODULE_NOT_FOUND' }
(node:31100) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
server starting on http://localhost:6001
socket connected Socket {
  io: 
   Manager {
     nsps: { '/': [Circular] },
     subs: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     opts: 
      { rejectUnauthorized: false,
        path: '/socket.io',
        hostname: 'localhost',
        secure: false,
        port: '6001' },
     _reconnection: true,
     _reconnectionAttempts: Infinity,
     _reconnectionDelay: 1000,
     _reconnectionDelayMax: 5000,
     _randomizationFactor: 0.5,
     backoff: Backoff { ms: 1000, max: 5000, factor: 2, jitter: 0.5, attempts: 0 },
     _timeout: 20000,
     readyState: 'open',
     uri: 'http://localhost:6001',
     connecting: [ [Circular] ],
     lastPing: null,
     encoding: false,
     packetBuffer: [],
     encoder: Encoder {},
     decoder: Decoder { reconstructor: null, _callbacks: [Object] },
     autoConnect: true,
     engine: 
      Socket {
        secure: false,
        agent: false,
        hostname: 'localhost',
        port: '6001',
        query: {},
        upgrade: true,
        path: '/socket.io/',
        forceJSONP: false,
        jsonp: true,
        forceBase64: false,
        enablesXDR: false,
        timestampParam: 't',
        timestampRequests: undefined,
        transports: [Array],
        transportOptions: {},
        readyState: 'open',
        writeBuffer: [],
        prevBufferLen: 0,
        policyPort: 843,
        rememberUpgrade: false,
        binaryType: null,
        onlyBinaryUpgrades: undefined,
        perMessageDeflate: [Object],
        pfx: null,
        key: null,
        passphrase: null,
        cert: null,
        ca: null,
        ciphers: null,
        rejectUnauthorized: false,
        forceNode: false,
        id: 'Pqnb9PmQ0gk0spDVAAAA',
        upgrades: [Array],
        pingInterval: 25000,
        pingTimeout: 5000,
        pingIntervalTimer: [Object],
        pingTimeoutTimer: [Object],
        transport: [Object],
        _callbacks: [Object] },
     skipReconnect: false,
     _callbacks: { '$open': [Array], '$packet': [Array], '$close': [Array] } },
  nsp: '/',
  json: [Circular],
  ids: 0,
  acks: {},
  receiveBuffer: [],
  sendBuffer: [],
  connected: true,
  disconnected: false,
  subs: 
   [ { destroy: [Function: destroy] },
     { destroy: [Function: destroy] },
     { destroy: [Function: destroy] } ],
  _callbacks: 
   { '$connecting': [ [Function: onConnecting] ],
     '$connect': [ [Function], [Function] ],
     '$connect_error': [ [Function] ],
     '$error': [ [Function] ] },
  id: 'Pqnb9PmQ0gk0spDVAAAA' }
found 0workspaces without schemaVersion
waiting for the migration to end
migration done
undefined 'test' undefined false
undefined 'I am too lazy to set the map title. I prefer getting lost.' undefined false
done done
? ?wdm?: Hash: f60b1ef75b83d16b6b6b
Version: webpack 4.7.0
Time: 14021ms
Built at: 07/07/2019 9:46:40 AM
                Asset      Size          Chunks             Chunk Names
               app.js  5.83 MiB             app  [emitted]  app
    canvas-wrapper.js  1.68 MiB  canvas-wrapper  [emitted]  canvas-wrapper
        google-app.js  3.72 MiB      google-app  [emitted]  google-app
           l-p-app.js  3.73 MiB         l-p-app  [emitted]  l-p-app
           app.js.map  6.07 MiB             app  [emitted]  app
canvas-wrapper.js.map  1.73 MiB  canvas-wrapper  [emitted]  canvas-wrapper
    google-app.js.map  3.83 MiB      google-app  [emitted]  google-app
       l-p-app.js.map  3.84 MiB         l-p-app  [emitted]  l-p-app
Entrypoint app = app.js app.js.map
Entrypoint google-app = google-app.js google-app.js.map
Entrypoint l-p-app = l-p-app.js l-p-app.js.map
Entrypoint canvas-wrapper = canvas-wrapper.js canvas-wrapper.js.map
[../node_modules/jquery/dist/jquery.js] ./node_modules/jquery/dist/jquery.js 274 KiB {l-p-app} {google-app} {app} [built]
[./app.js] ./src-ui/app.js 15.2 KiB {app} [built]
[./canvas-wrapper.js] ./src-ui/canvas-wrapper.js 2.54 KiB {canvas-wrapper} [built]
[./fixit/FixitPage.js] ./src-ui/fixit/FixitPage.js 12 KiB {l-p-app} {google-app} {app} [built]
[./google-app.js] ./src-ui/google-app.js 14 KiB {google-app} [built]
[./l-p-app.js] ./src-ui/l-p-app.js 14.3 KiB {l-p-app} [built]
[./map-editor/MapEditorPage.js] ./src-ui/map-editor/MapEditorPage.js 21.1 KiB {l-p-app} {google-app} {app} [built]
[./map-list/MapListPage.js] ./src-ui/map-list/MapListPage.js 22 KiB {l-p-app} {google-app} {app} [built]
[./minimal-canvas/canvas-with-background.js] ./src-ui/minimal-canvas/canvas-with-background.js 6.23 KiB {canvas-wrapper} [built]
[./passport/auth-store.js] ./src-ui/passport/auth-store.js 4.83 KiB {l-p-app} {google-app} [built]
[./passport/google/SplashPage.js] ./src-ui/passport/google/SplashPage.js 4.38 KiB {google-app} [built]
[./passport/l-p/LoginPage.js] ./src-ui/passport/l-p/LoginPage.js 5.27 KiB {l-p-app} [built]
[./passport/l-p/SplashPage.js] ./src-ui/passport/l-p/SplashPage.js 4.79 KiB {l-p-app} [built]
[./store-management.js] ./src-ui/store-management.js 3.11 KiB {l-p-app} {google-app} {app} [built]
[./workspace/WorkspaceListPage.js] ./src-ui/workspace/WorkspaceListPage.js 4.25 KiB {l-p-app} {google-app} {app} [built]
    + 1329 hidden modules
? ?wdm?: Compiled successfully.

Please advise!
Thank you!

**Comment by cdaniel** [comment]
Which branch are you running?

**Comment by xelcho** [comment]
Hey Chris!

I cloned from git, do you recommend a specific branch?

**Comment by cdaniel** [comment]
yep. Master contains unfinished work in progress.

Try https://github.com/LeadingEdgeForum/atlas2/tree/v2-service-branch. That's the one that is running at atlas2.wardleymaps.com.

**Comment by xelcho** [comment]
LOL  You rock I will do so!!!

Thanks!

**Comment by xelcho** [comment]
Please see the screen shots from hosted, my svr and yours. The cool icon is a black-box on mine. It seems to be a CSS diff.
![atlas2wardleymap](https://user-images.githubusercontent.com/30007489/60837037-356c4d80-a195-11e9-8b91-34bdf09d7e3f.PNG)

**Comment by cdaniel** [comment]
I am afraid it is not CSS. This is an issue with the underlying component (ReactResizeDetector). You may try to update the dependency to the latest version and see how does this work.

Or, quite contrary, you should try 2.2.0 (which I used and have not updated).

**Comment by xelcho** [comment]
Actually, the issue was with firefox vs chromium. Its all good.

Thanks for your support!
